steps:
  - name: ':hammer: Build'
    command: '/.buildkite/build.sh'
    agents:
      node: 'true'
      frontend: 'true'

  - wait

  - name: ':rocket: Deploy'
    command: '/.buildkite/deploy.sh'
    branches: 'develop'
    agents:
      node: 'true'
      frontend: 'true'

  - wait

  - trigger: 'pepino-demo-redeploy'
    label: ":rocket: Redeploy Pepino Demo"
    build:
      message: "Redeploy pepino-demo"
      commit: "HEAD"
      branch: "develop"
      env:
        BUILDKITE_BUILD_CREATOR_EMAIL: "developer@acklenavenue.com"
