steps:
  - name: ':hammer: Build'
    command: '/.buildkite/build.sh'
    agents:
      node: 'true'
      frontend: 'true'

  - wait

  - name: ':rocket: Deploy'
    command: '/.buildkite/deploy.sh'
    branches: 'develop'
    agents:
      node: 'true'
      frontend: 'true'

  - wait

  - name: ':rocket: ReDeploy Pepino-Demo'
    command: '/.buildkite/deploy.sh'
    branches: 'develop'
    agents:
      node: 'true'
      frontend: 'true'
    env:
      TRIGGER_ORG_SLUG: "acklen-avenue",
      TRIGGER_PIPELINE_SLUG: "pepino-demo-redeploy",
      TRIGGER_COMMIT: "HEAD",
      TRIGGER_BRANCH: "develop",
      TRIGGER_MESSAGE: "Oh hai :wave:"
